name: flutter_bloc_state_management
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ui
  cupertino_icons: ^1.0.2

  # bloc --state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # network
  pretty_dio_logger: ^1.3.1
  dio: ^5.4.0

  # json
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # models
  freezed: ^2.4.6
  json_serializable: ^6.7.1    
  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
flutter:
  uses-material-design: true